[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel", "numpy"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

[Project]
name = "spam"

